version: '2'
services:

  vault:
    image: vault:0.7.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: "true"
      VAULT_DEV_ROOT_TOKEN_ID: 'dev-token'
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

  vault-ui:
    container_name: vault-ui
    image: djenriquez/vault-ui
    ports:
      - "8300:8000"
    links:
      - vault
    environment:
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: TOKEN

  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    container_name: zookeeper-exhibitor
    ports:
      - "8400:8080"
      - "2181:2181"

  consul:
    image: consul:0.7.2
    container_name: consul
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
